config/routes.rb
Rails.application.routes.draw do
  resources :comments

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  resources :user_lists

  resources :users, except: [:new, :edit, :update, :destroy, :create] do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

  put 'change_status' => 'user_lists#change_status', as: :change_status
  put 'create' => 'comments#create', as: :create
  root 'movies#index'
  resources :movies do
    member do
      put "like", to: "movies#upvote"
      put "dislike", to: "movies#downvote"
    end
  end
  get 'about' => 'movies#about', as: :about

end

app/models/user_list.rb
class UserList < ActiveRecord::Base
  belongs_to :movie
  belongs_to :user
  # validates :movie_id, uniqueness: true
end

app/controllers/user_lists_controller.rb
class UserListsController < ApplicationController
  before_action :set_user_list, only: [:show, :edit, :update, :destroy]

  # GET /user_lists
  # GET /user_lists.json
  def index
    @user_lists = UserList.where(user_id: current_user.id)
    @users_lists = UserList.all
  end

  # GET /user_lists/1
  # GET /user_lists/1.json
  def show
  end

  # GET /user_lists/new
  def new
    @user_list = UserList.new
  end

  # GET /user_lists/1/edit
  def edit
  end

  # POST /user_lists
  # POST /user_lists.json
  def create
    @user_list = UserList.new(user_list_params)

    respond_to do |format|
      if @user_list.save
        format.html { redirect_to movies_path, notice: 'Filmul a fost adaugat in listele tale' }
        format.json { render :show, status: :created, location: @user_list }
      else
        format.html { render :new }
        format.json { render json: @user_list.errors, status: :unprocessable_entity }
      end
    end
    # redirect_to(:controller => 'movies', :action => 'index')
  end

  # PATCH/PUT /user_lists/1
  # PATCH/PUT /user_lists/1.json
  def change_status
    user_list = UserList.find_by(movie_id: params[:movie_id],user_id: params[:user_id])
      if user_list.status == false
        user_list.update(
          status: true
        )
      else
       user_list.status = false
       user_list.save
      end
      redirect_to user_path(current_user)
  end
  def update
    
  end

  # DELETE /user_lists/1
  # DELETE /user_lists/1.json
  def destroy
    # @user_list = current_user.user_lists.where(movie_id: params[:movie_id])
    # @user_list.destroy
    # respond_to do |format|
    #   format.html { redirect_to user_lists_url, notice: 'User list was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_list
      @user_list = UserList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_list_params
      params.permit(:status, :movie_id, :user_id)
    end

    

end

app/helpers/user_lists_helper.rb
module UserListsHelper

	# def watched
	# 	movie_id_aray = UserList.where(status: false).map{|l| l.movie_id }
	# 	Movie.find(movie_id_array)
	# end
end

app/views/user_lists/_form.html.erb
<%= form_for(@user_list) do |f| %>
  <% if @user_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_list.errors.count, "error") %> prohibited this user_list from being saved:</h2>

      <ul>
      <% @user_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label :movie_id %><br>
    <%= f.text_field :movie_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_lists/_status_list.html.erb
<div class="list-group">
	<ul>
  	<li>
 			<div class="row">
 				<div class="col-md-7 ">
 					<% if status_list.poster.blank? %>    
          	<%= link_to image_tag("default_size4.jpg"), movie_path(status_list)%>
        	<% else %>
				    <%= link_to image_tag(status_list.poster), movie_path(status_list) %>
					<% end %>
		  		  &nbsp;<% movies = status_list.title.split  %>
									<% movies.pop  %>
									<b><%= movies.join(' ')%></b>
								(<%= status_list.title.split.last %>)
		  		<% if current_user.id == @user.id %>
		  			<%= link_to 'Destroy', {:controller => :movies,:action => 'destroy', :id => status_list.id }, method: :delete, data: { confirm: 'Are you sure?' } %>
				</div>
				<div class="col-md-5">
				  	&nbsp;<%= form_tag change_status_path, :controller =>:movies, :method => "put"  do %>
				         	<%= hidden_field_tag :movie_id, status_list.id %>
				          <%= hidden_field_tag :user_id, @user.id  %>
				          <%= submit_tag "Muta in cealalta lista",:class=>"btn" %>
				  	<% end %>
					<% end %>
				</div>
			</div>
		</li>
	</ul>
</div>

app/views/user_lists/edit.html.erb
<h1>Editing User List</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_list %> |
<%= link_to 'Back', user_lists_path %>

app/views/user_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Users activity:</h2><br>
 
<% @users_lists.order(updated_at: :desc).each do |list| %>
  <ul>
    <li>
      <%= User.find_by(id: list.user_id).first_name %> 
      a adaugat in lista 
      <% if list.status == true %>
        "Vazute"
      <% else %>
        "Musai de vazut"
      <% end %>
      filmul "<%= Movie.find(list.movie_id).title %>"<br>
      at: <%= list.created_at %><hr>
    </li>
  </ul>
<% end %>
   

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Movie</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_lists.each do |user_list| %>
      <tr>
        <td><%= user_list.status %></td>
        <td><%= user_list.movie %></td>
        <td><%= user_list.user %></td>
        <td><%= link_to 'Show', user_list %></td>
        <td><%= link_to 'Edit', edit_user_list_path(user_list) %></td>
        <td><%= link_to 'Destroy', user_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/user_lists/new.html.erb
<h1>New User List</h1>

<%= render 'form' %>

<%= link_to 'Back', user_lists_path %>

app/views/user_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @user_list.status %>
</p>

<p>
  <strong>Movie:</strong>
  <%= @user_list.movie %>
</p>

<p>
  <strong>User:</strong>
  <%= @user_list.user %>
</p>

<%= link_to 'Edit', edit_user_list_path(@user_list) %> |
<%= link_to 'Back', user_lists_path %>