config/routes.rb
Rails.application.routes.draw do
  resources :comments

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  resources :user_lists

  resources :users, except: [:new, :edit, :update, :destroy, :create] do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

  put 'change_status' => 'user_lists#change_status', as: :change_status
  put 'create' => 'comments#create', as: :create
  root 'movies#index'
  resources :movies do
    member do
      put "like", to: "movies#upvote"
      put "dislike", to: "movies#downvote"
    end
  end
  get 'about' => 'movies#about', as: :about

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @movie_comments = Comment.where(movie_id: params[:id]).order(created_at: :desc)
    respond_to do |format|
      format.js {}
    end
  end

  # GET /comments/new
  def new
    @comment = Comment.new(movie_id: params[:id])
    respond_to do |format|
      format.js {}
    end
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.js {}
        format.html { redirect_to @comment.movie, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.movie, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @comment.movie, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :body, :movie_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_add_comment.html.erb
<%= form_for comment, :action => "create", :method => "post", remote: true do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id  %>
  <%= f.hidden_field :movie_id, value: comment.movie_id  %>
  <%= f.text_area :body %>
  <%= f.submit "Save comment" %>       
<% end %>

app/views/comments/_comment.html.erb
<ul class="list-group">
  <li class="list-group-item">
    <div class="commenterImage">
      <%= image_tag(comment.user.image, :class => "img-circle" )%>
      <%= comment.user.first_name %>
    </div>
    <div class="text">
    <p>
      <%= comment.body %> &nbsp;
      <% if current_user.comments.include?(comment) %>
    	  <%= link_to 'Edit', edit_comment_path(comment) %>
    	  <%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </p>
      <span class="sub-text">
        at
        <%= localize(comment.created_at,:format=>:long)%>
        </span>
    </div>
  </li>
</ul>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h5><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h5>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :user_id %>
  </div>
  <div class="field">
    
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.hidden_field :movie_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
 $('#comments').append("<%= escape_javascript (render partial: 'comment', object: @comment) %>");

app/views/comments/edit.html.erb
<h6>Editing Comment</h6>

<%= render 'form' %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/new.js.erb
$('#add_comment').html("<%= escape_javascript (render partial: 'add_comment', :object => @comment, :as => 'comment') %>")
 $('#new_comment :submit').click(function() {
 	$('#new_comment').hide();
 });

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Movie:</strong>
  <%= @comment.movie %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/comments/show.js.erb
var comments = $('#comments');
if (comments.is(':empty')) {
	comments.html("<%= escape_javascript (render partial: 'comment', collection: @movie_comments) %>");
	$('.showbutton').val('Hide Comments');
} else {
	comments.empty();
	$('.showbutton').val('Show Comments (<%= @movie_comments.count %>)');
}