config/routes.rb
Rails.application.routes.draw do
  resources :comments

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  resources :user_lists

  resources :users, except: [:new, :edit, :update, :destroy, :create] do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

  put 'change_status' => 'user_lists#change_status', as: :change_status
  put 'create' => 'comments#create', as: :create
  root 'movies#index'
  resources :movies do
    member do
      put "like", to: "movies#upvote"
      put "dislike", to: "movies#downvote"
    end
  end
  get 'about' => 'movies#about', as: :about

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movies</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <a href = "/"><img src="/assets/movieHunter1.png"/></a>
        </div>
        <div>
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Home</a></li>
            <li><%= link_to "About", about_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <li><%= link_to "All users", users_path %></li>
                <li><%= link_to "<span class='glyphicon glyphicon-user'></span> #{current_user.first_name}".html_safe, user_path(current_user) %></li>
                <li><%= link_to '<i class="glyphicon glyphicon-log-out"></i> Logout'.html_safe, destroy_user_session_path , :method => :delete %></li>
              <% else %>
                <li><%= link_to '<i class="glyphicon glyphicon-log-in"></i> Login'.html_safe, new_user_session_path %></li>
                <li><%= link_to '<span class="glyphicon glyphicon-user"></span>  Sign Up'.html_safe, new_user_registration_path %></li>
              <% end %>
            </ul>
        </div>
      </div>
    </nav>
        <%= yield %>  

    <div class="navbar navbar-default navbar-fixed-bottom footer" role="navigation">
      <div class="container">
        <div class="navbar-text pull-right">
          <p>&#169; 2015 Mada Iulia </p>
        </div>
        <div class="navbar-text pull-left">
          <p>Design and build with all the love in the world :)</p>
        </div>
      </div>
    </div>
    <%= javascript_include_tag 'application' %>
  </body>
</html>